### PR TITLE
faq_4 title & text

### PR DESCRIPTION
**Pull request by 10cents**
Have you updated how it works in future versions? Here is how it works on my phone:

When you add a widget to your home screen from the widget list on your device the colour configuration options appears. You will see a square at the bottom left corner, just press it to pick a new colour. You can use the slider for adjusting the alpha too.
The option to resize it appears if you drag the widget on the screen.

### CODE REVIEW

**Comment by tibbi** [comment]
What do you mean? It works exactly as you say, I havent changed it. This is just about the colors, not resizing.

**Comment by 10cents** [comment]
As I read the new faq I should be able to activate the colour configuration by dragging the already installed widget. I can not, I only activate resizing. But when I _add_ a widget I can adjust the colour by clicking at the square (not the squares).

**Comment by 10cents** [comment]
Oh, you mean as I drag a widget _onto_ your home screen, I read 'drag' as 'move'.

**Comment by tibbi** [comment]
Ye I mean that initial drag, when you pull the widget from the widgets list on the home screen. On some devices clicking is enough, but sometimes you drag it. Most widgets have 2 color squares for the text and the background, only the flashlight has one.

**Comment by 10cents** [comment]
I better change the translation then

**Comment by 10cents** [comment]
BTW what du you mean with 'only the flashlight has one'?

**Comment by tibbi** [comment]
the flashlight widget has 1 colored square as theres no background, other apps have 2 for changing both the text and background

**Comment by 10cents** [comment]
So some phones use flashlight widget, other phones use another kind of widget. And you have to develop both types?

**Comment by tibbi** [comment]
I mean the Simple Flashlight app widget has 1 square, other app widgets like Simple Music Player, Calendar etc have two.

**Comment by 10cents** [comment]
:) Ok. I apologize for all these questions. But in the end I think it may cause better translations. Calendar widget also has 1 square :)

**Comment by tibbi** [comment]
Which one? I guess theres 2 too, you just lowered the alpha so it is transparent. Try sliding the alpha bar.

**Comment by 10cents** [comment]
Yep, you're right, thanks!

**Comment by tibbi** [comment]
ye I will redo the widget config screen someday to make it more obvious, but I dont want to waste any time on it now.

**Comment by 10cents** [comment]
If you are going to improve it some day I think it would be good to be able to adjust a widget already present on the screen. And maybe frame the squares so that they are both visible if some idiots as me lower the alpha so it is completely transparent.

**Comment by tibbi** [comment]
ye I will add an option to change widget colors without recreating them at the "Customize colors" screen in settings. You arent an idiot, it is just bad UI :) That screen is pretty much the only one which hasnt changed since the apps were created. It surely needs some refreshment.

**Comment by 10cents** [comment]
Well, I admit that I am not a genuine idiot, but enough idiot to forget to use quotation marks when appropriate. :-)

**Pull request merged**
