### PR TITLE
fix: navigation bar paddings for landscape mode

### PR DESCRIPTION
**Pull request by FunkyMuse**

### CODE REVIEW

**Comment by tibbi** [comment]
I think this should be solved in some generic way so that we dont have to think about it in all apps screens. The top actionmenu color shouldnt be behind the navigation either, just like the divider bar. Check Simple Clock, while the Settings page works well, the About doesnt.

**Comment by FunkyMuse** [comment]
> 

i think my latest change fixes this, accordingly as at Simple Clock

**Comment by tibbi** [comment]
should be good, will do more testing in a real app. Thanks

**Comment by tibbi** [comment]
if the navigation bar is white, buttons Back, Home and Recents should be dark

**Comment by tibbi** [comment]
and in landscape mode the navigation is always dark, even when it should be light

**Comment by FunkyMuse** [comment]
> if the navigation bar is white, buttons Back, Home and Recents should be dark

Which should be the source color for all?

**Comment by tibbi** [comment]
what source color you mean? the navigation bar itself properly toggles light/dark color, so just the buttons have to be adjusted too

**Comment by FunkyMuse** [comment]
> what source color you mean? the navigation bar itself properly toggles light/dark color, so just the buttons have to be adjusted too

Oh you meant the navigation bar's (3 buttons) colors, alright, gotcha.

**Pull request merged**
