### PR TITLE
Add Kurdish language iso 639-1 and iso 639-3 code

### PR DESCRIPTION
**Pull request by GoRaN9O**
Add Kurdish language.

### CODE REVIEW

**Comment by tibbi** [comment]
why are you adding the language if you havent even translated any strings yet? This file isnt about the keyboard language.

**Comment by GoRaN909** [comment]
> why are you adding the language if you havent even translated any strings yet? This file isnt about the keyboard language.

I added because the keyboard app required to the layout name and I translated the Simple-Keyboard before I add the layout look here is the translated stings of [ckb](https://github.com/SimpleMobileTools/Simple-Keyboard/blob/main/app/src/main/res/values-ckb/strings.xml)

**Comment by tibbi** [comment]
right, this file is about strings though, not the keyboard languages. Will take a look at those soon.

**Comment by GoRaN909** [comment]
> right, this file is about strings though, not the keyboard languages. Will take a look at those soon.

Okay I just started translating some simple tools apps I will do my to completely translate all of them but for now only the keyboard app is important to me :)

**Pull request closed without merging**
