### PR TITLE
feat: About Activity migration to Compose

### PR DESCRIPTION
**Pull request by FunkyMuse**
also created re-usable Settings components

### CODE REVIEW

**Comment by tibbi** [comment]
there is some big margin at the bottom, under Made with heart in Slovakia. And Github icon isnt visible on dark theme.

**Comment by naveensingh** [comment]
@tibbi  @FunkyMuse I haven't checked the code but with the latest commons, the **Rate us** dialog on About page is using incorrect colors on the light theme (dynamic):

**Comment by naveensingh** [comment]
Also, is that large padding between the top bar and "SUPPORT" category text intentional? Doesn't look quite right to me.

**Comment by FunkyMuse** [comment]
> @tibbi @FunkyMuse I haven't checked the code but with the latest commons, the **Rate us** dialog on About page is using incorrect colors on the light theme (dynamic): 

I'll check that, thanks

**Comment by FunkyMuse** [comment]
> 

This wasn't my decision, this went into few iterations and if @tibbi decides to change it further please let me know and I will.

**Comment by FunkyMuse** [comment]
> 

This wasn't my decision, this went into few iterations and if @tibbi decides to change it further please let me know and I will.

**Comment by tibbi** [comment]
sure, lets make the top padding a bit smaller

**Comment by FunkyMuse** [comment]
> sure, lets make the top padding a bit smaller

Sure, that'll make every title's top padding smaller

**Comment by naveensingh** [comment]
actually, the dialog does not use proper colors in the dark theme too:

**Comment by naveensingh** [comment]
> Sure, that'll make every title's top padding smaller

you mean the category title right? The top app bar title is fine.

**Comment by FunkyMuse** [comment]
> > Sure, that'll make every title's top padding smaller
> 
> you mean the category title right? The top app bar title is fine.

yes

**Comment by FunkyMuse** [comment]
> actually, the dialog does not use proper colors in the dark theme too:
> 

I don't modify the dialog themes, didn't touch that code.

**Comment by naveensingh** [comment]
right, I just checked and it is broken on an older version of SMS Messenger too so it probably was always like that. I guess it'll fixed during compose migration.

**Comment by FunkyMuse** [comment]
> right, I just checked and it is broken on an older version of SMS Messenger too so it probably was always like that. I guess it'll fixed during compose migration.

Yes it will be, they will be completely migrated to our theming logic as we have it now.

**Pull request merged**
