### PR TITLE
update nl strings.xml

### PR DESCRIPTION
**Pull request by Joppla**
Names of days with small start letter in stead of capital according to Dutch spelling rules.

### CODE REVIEW

**Comment by tibbi** [comment]
Lowercase letters dont really fit into the given context so I want to keep them uppercase. Thanks thouhg

**Comment by Joppla** [comment]
Thanks for your comment. Maybe I see another context, but on the clockwidget, see attachment,  in Dutch it should be small first letters in stead of capital. And for Friday it should be "vrij" in stead of "vri".
-- 
Met vriendelijke groet,
Jop

Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by tibbi** [comment]
most strings are limited to 3 characters there, I dont want to make it 4 for now. Seems like it wasnt really an issue to anyone so far. Thanks

**Comment by Joppla** [comment]
According to the official spelling rules of Dutch, it's advised to use the 2 letter form. ma di wo do vr za zo
-- 
Met vriendelijke groet,
Jop

Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

Tibor Kaputa <notifications@github.com> schreef op 13 februari 2020 20:54:18 CET:

**Pull request closed without merging**
