### PR TITLE
fix querying latest media

### PR DESCRIPTION
**Pull request by KryptKode**
# Notes
- add support for `queryArgs` `Bundle` on SDK 30+ (Android 11+) in the `queryCursorDesc` method
- found it broken in the Simple Camera app to display the last taken photo when the app starts,
-  it is also used in the Simple Gallery app to determine whether to load the directories as an optimisation

# Testing
-  using the query args bundle only works well on SDK 30+. 
- the test details are [here](https://lumpy-scorpion-7f2.notion.site/Testing-Limit-Query-ba0bbdd3ccc741c9940fefeaf43b83c5)

### CODE REVIEW

**Comment by tibbi** [comment]
are you sure the limiting works? We had to do it like https://github.com/SimpleMobileTools/Simple-Dialer/pull/379 for the dialers recent calls

**Comment by KryptKode** [comment]
> are you sure the limiting works? We had to do it like [SimpleMobileTools/Simple-Dialer#379](https://github.com/SimpleMobileTools/Simple-Dialer/pull/379) for the dialers recent calls

That method only works for Call logs as far as I know. I tested and the fix works on Android 11 and Android 9. 
Still testing at the moment with the Gallery App. 
Do you know if other apps use the `getLatestMediaId` and `getLatestMediaByDateId`  methods?

**Comment by KryptKode** [comment]
Converting to draft until fully tested.

**Comment by tibbi** [comment]
there are no other apps using it

**Comment by KryptKode** [comment]
Just tested again and found that using the query args bundle only works well on SDK 30+. 
On lower android versions, the cursor count becomes more than 1. 
So I adjusted the if statement to use `isRPlus`. I will publish the test details soon

**Comment by tibbi** [comment]
thats a long report. So can I merge this PR or you want to add anything else to it?

**Comment by KryptKode** [comment]
Yes, you can merge

**Pull request merged**
