### PR TITLE
feat: more dialog stuff

### PR DESCRIPTION
**Pull request by FunkyMuse**
- create new folder dialog
- enter password
- folder lock notice
- bottom sheet chooser

### CODE REVIEW

**Comment by tibbi** [comment]
Im getting compile errors

**Comment by FunkyMuse** [comment]
> Im getting compile errors, unresolved dialogBorder

I'll check in a bit

**Comment by tibbi** [comment]
1. nothing happens at clicking the path at Create new folder
2. bottom sheet should close automatically after picking an item
3. cannot launch the bottom sheet choose multiple times. Once it hides, no button clicks work.

**Comment by FunkyMuse** [comment]
> 1. nothing happens at clicking the path at Create new folder
> 
>     2. bottom sheet should close automatically after picking an item
> 
>     3. cannot launch the bottom sheet choose multiple times. Once it hides, no button clicks work.

1. Nothing should as of now
2, 3: Will fix soon

**Comment by FunkyMuse** [comment]
@tibbi we can merge this one while adding the things later on, or you prefer to have them too?

They're dependant on other dialogs that I think @esensar is working on?

**Comment by tibbi** [comment]
bottom sheet chooser appears instantly, doesnt properly pull up with an animation

**Comment by FunkyMuse** [comment]
> bottom sheet chooser appears instantly, doesnt properly pull up with an animation

I'll see if it's possible soon, if not I'll open a feature request with Google

**Comment by FunkyMuse** [comment]
Hmmm, the show and hide functions are animated already, I'll see why this is the case 🤔

The showing is not animated, it's like stuck, but hiding is animated, is it the same on your side?

**Comment by tibbi** [comment]
ye, like something was still loading on the main thread at showing, so by the time it loads properly, the animation is already done

**Comment by tibbi** [comment]
thanks, should be good now

**Pull request merged**
