### PR TITLE
Add support for biometric ID in SecurityDialog when targeting API 30+

### PR DESCRIPTION
**Pull request by qwertyfinger**
Modifies SecurityDialog to use androidx biometric library if the `targetSdkVersion` is 30+.

### CODE REVIEW

**Comment by qwertyfinger** [comment]
You can check out the update Notes version that uses this commons version here: https://github.com/qwertyfinger/Simple-Notes/tree/feature/biometric-lock-api30

**Comment by tibbi** [comment]
1. the top dialog label still shows "Fingerprint", lets replace it with "Biometry" or something like that
2. when a note is locked and you click "Show content", or "Unlock note" lets skip our dialog and show the system one right away.
Otherwise it looks great, looks like it wont need an extra permission either.

**Comment by qwertyfinger** [comment]
> 
> 
>     1. the top dialog label still shows "Fingerprint", lets replace it with "Biometry" or something like that
> 
>     2. when a note is locked and you click "Show content", or "Unlock note" lets skip our dialog and show the system one right away.
>        Otherwise it looks great, looks like it wont need an extra permission either.

Thanks, will make those adjustments 👍

**Comment by qwertyfinger** [comment]
@tibbi Updated this and the example Notes branch as well: https://github.com/qwertyfinger/Simple-Notes/tree/feature/biometric-lock-api30

**Comment by tibbi** [comment]
seems to work just fine, Ill test it in other apps too. Thanks!

**Comment by qwertyfinger** [comment]
> 
> 
> seems to work just fine, Ill test it in other apps too. Thanks!

I tested the File Manager – worked fine. We could even show the new biometric experience for other apps too if we wanted to.

**Comment by tibbi** [comment]
let's use the previous "Fingerprint" tab title on target SDK 29, it always shows Biometrics now

**Comment by qwertyfinger** [comment]
> 
> 
> let's use the previous "Fingerprint" tab title on target SDK 29, it always shows Biometrics now

Ok, I will update it later in a separate PR then

**Pull request merged**
